# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secrets', '0002_auto_20160919_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secrets.Secret')),
            ],
        ),
    ]
